name: Deploy to EC2

on:
  push:
    branches:
      - master   # or master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          sudo su - << 'EOF'
          cd /task-management
          git pull origin master
          npm install
          pm2 restart backend
          EOF
